DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS ExpertClasses;
DROP TABLE IF EXISTS ExpertSubjects;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Classes;

CREATE TABLE Users
(
	user_id INT AUTO_INCREMENT NOT NULL,
	username VARCHAR(255) NOT NULL,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY Key (user_id)
) ENGINE=InnoDB;

CREATE TABLE Subjects
(
	subject_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	description VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE ExpertSubjects
(
	user_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	subject_id INT NOT NULL,
		FOREIGN KEY (subject_id)
			REFERENCES Subjects (subject_id)
			ON UPDATE CASCADE
			ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE Classes
(
	class_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	description VARCHAR(255) NOT NULL 
) ENGINE=InnoDB;


CREATE TABLE ExpertClasses
(
	user_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	class_id INT NOT NULL,
		FOREIGN KEY (class_id)
			REFERENCES Classes (class_id)
			ON UPDATE CASCADE
			ON DELETE CASCADE
) ENGINE=InnoDB;

